### ISSUE TITLE
RTL other Ghost themes in the same fashion

### ISSUE THREAD

**Issue by hadifarnoud** [mderazon/Casper-RTL#2]
I want to RTL other themes to work just like this one with tags. I have a blog which the default format would be RTL. I can manage that with CSS but it would be great if I can add English or LTR tag to my post and text becomes LTR.

how do you do that? I couldn't find any logic for tag related css changes.

**Comment by mderazon** [comment]
first i've added the relevant classes to the css files - [here](https://github.com/mderazon/Casper-RTL/blob/master/assets/css/screen.css#L172)

Then it's basically tweaking with hbs and casper's api

I've wrapped the `post.hbs` content with `content-holder` and set it's class with the available tags - see [here](https://github.com/mderazon/Casper-RTL/commit/19c4a80021c3cebba687aa190f3c1390f2dfbe9a). did a similar thing with the [index file](https://github.com/mderazon/Casper-RTL/commit/c2cca4991d08f17d1a5d943803e424a86e357730).

I had some mistakes along the way that I needed to fix and commit, if you follow the [commit trail](https://github.com/mderazon/Casper-RTL/commits/master?page=2) and look for my changes (only had 4 commits there) you'll see.

I see that Casper has changed since and I guess Ghost API has changed as well but the general idea is the same.

Hope it helps...

**Comment by hadifarnoud** [comment]
clever. what about Ghost compose page? that's not RTL either and makes writing hard.

**Comment by mderazon** [comment]
personally I never used it (and I actually moved away from ghost to [harp](http://harpjs.com/)).

I prefer using a local markdown editor (there are tons of them) that supports css (so I can RTL the thing) then just paste it into ghost editor...

**Comment by hadifarnoud** [comment]
cheers

**Comment by hadifarnoud** [comment]
@mderazon can you please recommend a few Markdown editors that support RTL and has Wysiwyg?

I've been searching around but every editor has its problems

**Comment by mderazon** [comment]
@hadifarnoud what os are you running ?

**Comment by mderazon** [comment]
I'm currently using Macdown for OSX - http://macdown.uranusjr.com/
I have used MdCharm before for windows and I think it supported CSS - http://www.mdcharm.com/

**Comment by hadifarnoud** [comment]
thank you
